import type { Product } from "@/types/product";
import type { Category } from "@/types/category";
import type { LocaleStrings } from "@/types/locales";
import { unsplash } from "@/lib/images";

/**
 * Placeholder product catalog. Photos are free Unsplash placeholders
 * (unsplash.com/license). To use real product shots, put them in
 * `public/images/products/` and replace each `unsplash("...")` with the file's
 * path, e.g. `url: "/images/products/classic-black-1.jpg"`. No other code
 * needs to change.
 */
export const mockProducts: Product[] = [
  {
    id: "p1",
    slug: "classic-black",
    name: "Classic Black",
    category: "sunglasses",
    price: 39,
    mrp: 49,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 120,
    images: [
      { url: unsplash("1584036553516-bf83210aa16c"), alt: "Classic Black sunglasses" },
      { url: unsplash("1623071280989-20f220c6e609"), alt: "Classic Black sunglasses, alternate view" },
    ],
    colors: ["Jet Black", "Tortoise"],
    lensColors: ["Grey Gradient"],
    shape: "square",
    gender: "unisex",
    features: ["UV400 protection", "Gradient lenses", "Lightweight acetate frame", "Spring hinges"],
    badges: ["Bestseller", "Sale"],
    inStock: true,
    description: "Timeless design, everyday style. A browline frame with gradient lenses for clear, comfortable vision.",
  },
  {
    id: "p2",
    slug: "retro-brown",
    name: "Retro Brown",
    category: "sunglasses",
    price: 35,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 78,
    images: [
      { url: unsplash("1631161475251-9c1b87c34c1a"), alt: "Retro Brown sunglasses" },
    ],
    colors: ["Jet Black"],
    lensColors: ["Brown Gradient"],
    shape: "rectangle",
    gender: "unisex",
    features: ["UV400 protection", "Gradient lenses", "Lightweight and durable"],
    badges: ["New"],
    inStock: true,
    description: "A slim rectangle with warm brown gradient lenses. A little retro, a lot of attitude.",
  },
  {
    id: "p3",
    slug: "golden-hour",
    name: "Golden Hour",
    category: "sunglasses",
    price: 45,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 96,
    images: [
      { url: unsplash("1511499767150-a48a237f0083"), alt: "Golden Hour sunglasses" },
    ],
    colors: ["Gold"],
    lensColors: ["Green"],
    shape: "round",
    gender: "unisex",
    features: ["UV400 protection", "Metal wire frame", "Adjustable nose pads"],
    badges: ["Bestseller"],
    inStock: true,
    description: "Featherweight gold wire and bottle-green lenses. Made for long lunches and longer sunsets.",
  },
  {
    id: "p4",
    slug: "sand-dune",
    name: "Sand Dune",
    category: "sunglasses",
    price: 42,
    mrp: 52,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 64,
    images: [
      { url: unsplash("1508296695146-257a814070b4"), alt: "Sand Dune sunglasses" },
    ],
    colors: ["Cream", "Gold"],
    lensColors: ["Brown"],
    shape: "cat-eye",
    gender: "women",
    features: ["UV400 protection", "Acetate and metal frame", "Lightweight fit"],
    badges: ["Sale"],
    inStock: true,
    description: "A soft cream cat-eye with gold detailing. Beach-ready, city-proof.",
  },
  {
    id: "p5",
    slug: "matte-green",
    name: "Matte Green",
    category: "sunglasses",
    price: 32,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 51,
    images: [
      { url: unsplash("1653038282189-803202722a05"), alt: "Matte Green sunglasses" },
    ],
    colors: ["Matte Green", "Jet Black"],
    lensColors: ["Black"],
    shape: "square",
    gender: "men",
    features: ["UV400 protection", "Polarised lenses", "Matte finish"],
    inStock: true,
    description: "Low-key matte green, compact square shape, zero effort required.",
  },
  {
    id: "p6",
    slug: "weekend-wayfarer",
    name: "Weekend Wayfarer",
    category: "sunglasses",
    price: 36,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 142,
    images: [
      { url: unsplash("1473496169904-658ba7c44d8a"), alt: "Weekend Wayfarer sunglasses" },
      { url: unsplash("1566421966482-ad8076104d8e"), alt: "Weekend Wayfarer sunglasses, alternate view" },
    ],
    colors: ["Jet Black"],
    lensColors: ["Green"],
    shape: "wayfarer",
    gender: "unisex",
    features: ["UV400 protection", "Polarised lenses", "Durable acetate frame"],
    badges: ["Bestseller"],
    inStock: true,
    description: "The shape everyone knows, tuned for sand, sea and Sunday plans.",
  },
  {
    id: "p7",
    slug: "blush-wayfarer",
    name: "Blush Wayfarer",
    category: "sunglasses",
    price: 38,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 57,
    images: [
      { url: unsplash("1718774144019-2b47ffdb84a7"), alt: "Blush Wayfarer sunglasses" },
    ],
    colors: ["Jet Black"],
    lensColors: ["Purple"],
    shape: "wayfarer",
    gender: "women",
    features: ["UV400 protection", "Tinted lenses", "Lightweight and durable"],
    badges: ["New"],
    inStock: true,
    description: "A classic wayfarer with a dusky purple lens that makes everything look like golden hour.",
  },
  {
    id: "p8",
    slug: "tortoise-pop",
    name: "Tortoise Pop",
    category: "sunglasses",
    price: 44,
    mrp: 55,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 88,
    images: [
      { url: unsplash("1559070081-648fb00b2ed1"), alt: "Tortoise Pop sunglasses" },
    ],
    colors: ["Tortoise"],
    lensColors: ["Brown"],
    shape: "wayfarer",
    gender: "unisex",
    features: ["UV400 protection", "Hand-polished acetate", "Spring hinges"],
    badges: ["Sale"],
    inStock: true,
    description: "Warm tortoiseshell that goes with literally everything you own.",
  },
  {
    id: "p9",
    slug: "sky-transparent",
    name: "Sky Transparent",
    category: "sunglasses",
    price: 34,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 45,
    images: [
      { url: unsplash("1577803645773-f96470509666"), alt: "Sky Transparent sunglasses" },
    ],
    colors: ["Clear"],
    lensColors: ["Brown"],
    shape: "round",
    gender: "unisex",
    features: ["UV400 protection", "Transparent acetate", "Lightweight fit"],
    badges: ["New"],
    inStock: true,
    description: "A crystal-clear round frame with honey lenses. Light, bright and easy to wear.",
  },
  {
    id: "p10",
    slug: "night-owl",
    name: "Night Owl",
    category: "sunglasses",
    price: 40,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 102,
    images: [
      { url: unsplash("1600024914363-d9bf85e438f0"), alt: "Night Owl sunglasses" },
      { url: unsplash("1623071280879-8a2542eac274"), alt: "Night Owl sunglasses, alternate view" },
    ],
    colors: ["Jet Black", "Silver"],
    lensColors: ["Black"],
    shape: "square",
    gender: "men",
    features: ["UV400 protection", "Metal and acetate frame", "Spring hinges"],
    badges: ["Limited"],
    inStock: false,
    description: "Sharp browline, deep black lenses. Back soon.",
  },
  {
    id: "p11",
    slug: "trailblazer-wrap",
    name: "Trailblazer Wrap",
    category: "sports",
    price: 49,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 73,
    images: [
      { url: unsplash("1708799366365-a24608103bed"), alt: "Trailblazer Wrap sports sunglasses" },
      { url: unsplash("1708799366362-f3533dd266c2"), alt: "Trailblazer Wrap sports sunglasses, alternate view" },
    ],
    colors: ["Jet Black"],
    lensColors: ["Black"],
    shape: "sport",
    gender: "unisex",
    features: ["UV400 protection", "Impact-resistant lenses", "Rubberised grip", "Wraparound coverage"],
    badges: ["Bestseller"],
    inStock: true,
    description: "Grippy, featherweight wraparound built to stay put on the trail and the bike.",
  },
  {
    id: "p12",
    slug: "neon-flash",
    name: "Neon Flash",
    category: "sports",
    price: 55,
    mrp: 65,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 90,
    images: [
      { url: unsplash("1675798828659-5558961c38db"), alt: "Neon Flash sports sunglasses" },
    ],
    colors: ["Jet Black"],
    lensColors: ["Mirror Red"],
    shape: "sport",
    gender: "unisex",
    features: ["UV400 protection", "Mirrored shield lens", "Impact-resistant", "Ventilated frame"],
    badges: ["Sale", "Limited"],
    inStock: true,
    description: "A full-shield mirror lens that turns heads on every descent.",
  },
  {
    id: "p13",
    slug: "featherlight-round",
    name: "Featherlight Round",
    category: "eyeglasses",
    price: 45,
    currency: "EUR",
    rating: 4.7,
    reviewCount: 66,
    images: [
      { url: unsplash("1686165863154-b8f9d69add82"), alt: "Featherlight Round eyeglasses" },
      { url: unsplash("1686165862816-ed104011f9a9"), alt: "Featherlight Round eyeglasses, alternate view" },
    ],
    colors: ["Matte Green"],
    lensColors: ["Clear"],
    shape: "round",
    gender: "unisex",
    features: ["Ultra-light frame", "Anti-glare ready", "Adjustable nose pads"],
    badges: ["New"],
    inStock: true,
    description: "Barely-there round frames you will forget you are wearing.",
  },
  {
    id: "p14",
    slug: "clearview-round",
    name: "Clearview Round",
    category: "eyeglasses",
    price: 49,
    currency: "EUR",
    rating: 4.8,
    reviewCount: 110,
    images: [
      { url: unsplash("1646084081219-1090f72a531c"), alt: "Clearview Round eyeglasses" },
    ],
    colors: ["Jet Black", "Gold"],
    lensColors: ["Clear"],
    shape: "round",
    gender: "unisex",
    features: ["Metal frame", "Anti-glare ready", "Adjustable nose pads"],
    badges: ["Bestseller"],
    inStock: true,
    description: "Black and gold round frames for clear vision with a bit of shine.",
  },
  {
    id: "p15",
    slug: "vintage-browline",
    name: "Vintage Browline",
    category: "eyeglasses",
    price: 52,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 58,
    images: [
      { url: unsplash("1574258495973-f010dfbb5371"), alt: "Vintage Browline eyeglasses" },
    ],
    colors: ["Tortoise", "Silver"],
    lensColors: ["Clear"],
    shape: "square",
    gender: "men",
    features: ["Acetate and metal frame", "Spring hinges", "Prescription ready"],
    inStock: true,
    description: "The classic browline, cut sharper and priced friendlier.",
  },
  {
    id: "p16",
    slug: "tortoise-optic",
    name: "Tortoise Optic",
    category: "eyeglasses",
    price: 46,
    mrp: 56,
    currency: "EUR",
    rating: 4.5,
    reviewCount: 39,
    images: [
      { url: unsplash("1603578119639-798b8413d8d7"), alt: "Tortoise Optic eyeglasses" },
    ],
    colors: ["Tortoise"],
    lensColors: ["Clear"],
    shape: "round",
    gender: "women",
    features: ["Hand-polished acetate", "Prescription ready", "Spring hinges"],
    badges: ["Sale"],
    inStock: true,
    description: "Rich tortoiseshell with a soft round shape. Studious, never boring.",
  },
  {
    id: "p17",
    slug: "gold-hex",
    name: "Gold Hex",
    category: "eyeglasses",
    price: 54,
    currency: "EUR",
    rating: 4.4,
    reviewCount: 27,
    images: [
      { url: unsplash("1646083774155-2a40b675641d"), alt: "Gold Hex eyeglasses" },
    ],
    colors: ["Gold"],
    lensColors: ["Clear"],
    shape: "square",
    gender: "women",
    features: ["Metal wire frame", "Adjustable nose pads", "Prescription ready"],
    badges: ["New"],
    inStock: true,
    description: "A hexagonal gold wire frame for people who like their basics a bit bolder.",
  },
  {
    id: "p18",
    slug: "silver-round",
    name: "Silver Round",
    category: "eyeglasses",
    price: 44,
    currency: "EUR",
    rating: 4.3,
    reviewCount: 31,
    images: [
      { url: unsplash("1614715838608-dd527c46231d"), alt: "Silver Round eyeglasses" },
    ],
    colors: ["Silver"],
    lensColors: ["Clear"],
    shape: "round",
    gender: "unisex",
    features: ["Metal wire frame", "Lightweight fit", "Prescription ready"],
    inStock: true,
    description: "Minimal silver rounds that go with every look.",
  },
  {
    id: "p19",
    slug: "screen-saver",
    name: "Screen Saver",
    category: "blue-light",
    price: 39,
    currency: "EUR",
    rating: 4.6,
    reviewCount: 84,
    images: [
      { url: unsplash("1556306510-31ca015374b0"), alt: "Screen Saver blue-light glasses" },
    ],
    colors: ["Jet Black"],
    lensColors: ["Clear"],
    shape: "rectangle",
    gender: "unisex",
    features: ["Blue-light filtering lenses", "Anti-glare coating", "Lightweight frame"],
    badges: ["Bestseller"],
    inStock: true,
    description: "Blue-light filtering lenses in a bold black rectangle, for long days at the screen.",
  },
];

/**
 * Temporary category source until the categories endpoint is available.
 * Copy is resolved through the active locale; category identity stays data.
 */
export function getMockCategories(strings: LocaleStrings): Category[] {
  return [
    {
      id: "sunglasses",
      name: strings.shopByCategory.categories.sunglasses.name,
      description: strings.shopByCategory.categories.sunglasses.description,
      image: "sunglasses",
      slug: "sunglasses",
      bgColor: "primary",
    },
    {
      id: "eyeglasses",
      name: strings.shopByCategory.categories.eyeglasses.name,
      description: strings.shopByCategory.categories.eyeglasses.description,
      image: "eyeglasses",
      slug: "eyeglasses",
      bgColor: "secondary",
    },
    {
      id: "sports",
      name: strings.shopByCategory.categories.sports.name,
      description: strings.shopByCategory.categories.sports.description,
      image: "sports",
      slug: "sports",
      bgColor: "accentBlue",
    },
  ];
}
